### ISSUE TITLE
Duplicated Undebuggable.ipa File

### ISSUE THREAD

**Issue by raulsiles** [commjoen/uncrackable_app#7]
The Undebuggable.ipa file available under the "Level1.ipa" directory for both iOS apps, Level 1 and Level 2, is the same IPA file (notice that for both the folder is named "Level1.ipa"):

https://github.com/commjoen/uncrackable_app/tree/master/iOS/Level1/UnDebuggable/Level1.ipa/
https://github.com/commjoen/uncrackable_app/tree/master/iOS/Level2/UnDebuggable/Level1.ipa/

The SHA1 hash for both is: d5efad4191a9a1af08739664e52c3089dc676dcc.

**Comment by commjoen** [comment]
Thank you for reporting! I will look into it and get back to you :)

**Comment by commjoen** [comment]
It seems that ipa2 was not written propperly to the filesystem. We will prepare another release.
